POST localhost:8080/api/v1/article/moderator/create
Content-Type:  application/json
Authorization: Basic MTIzNDU2Nzg6MTIzNDU=

{
  "title": "title1",
  "description": "description1",
  "content": "content1",
  "imageId": "5c19640a-bcd6-42cc-ac34-06ba851548d1",
  "regionId": 1,
  "categoryId": 1,
  "articleType": [1, 2],
  "articleTag": [1, 2, 3]
}