POST localhost:8080/api/v1/category/admin/create
Content-Type:  application/json
Authorization: Basic Kzk5ODkxNTI1NDQ3NToxMjM0

{
  "orderNumber": 1,
  "nameEng": "Sport eng",
  "nameRu": "Sport ru",
  "nameUz": "Sport uz"
}